
(function(){
  function closeWelcome(){
    var el=document.getElementById('furbypedia-welcome-splash');
    if(!el) return;
    el.style.transition='opacity .22s ease';
    el.style.opacity='0';
    setTimeout(function(){ el.remove(); },230);
  }
  document.addEventListener('DOMContentLoaded', function(){
    var btn=document.getElementById('fw-start-btn');
    if(btn) btn.addEventListener('click', closeWelcome);
    document.addEventListener('keydown', function(e){
      if(e.key==='Escape') closeWelcome();
    });
  });
})();



const data=window.FURBY_DATA||[];const key=x=>String(x.id);const $=id=>document.getElementById(id);let owned=new Set(JSON.parse(localStorage.getItem('furby-owned')||'[]'));let favorites=new Set(JSON.parse(localStorage.getItem('furby-favorites')||'[]'));let records=JSON.parse(localStorage.getItem('furby-records')||'{}');let view='collectible';let sortMode='default';let deferredInstallPrompt=null;let currentFurbyIndex=-1,currentKey=null;let touchStartX=0,touchStartY=0;
function imgFallback(img){img.onerror=null;img.style.display='none';const p=img.parentElement;if(p&&!p.querySelector('.imgFallback')){const d=document.createElement('div');d.className='imgFallback';d.textContent='🧸';d.style.fontSize='56px';d.style.opacity='.55';p.appendChild(d)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function saveAll(){localStorage.setItem('furby-owned',JSON.stringify([...owned]));localStorage.setItem('furby-favorites',JSON.stringify([...favorites]));localStorage.setItem('furby-records',JSON.stringify(records))}
function unique(field){return [...new Set(data.map(x=>x[field]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es'))}function fill(id,vals){vals.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$(id).appendChild(o)})}fill('era',unique('era'));fill('collection',unique('collection'));fill('generation',unique('generation'));
function collectible(){return data.filter(x=>x.status==='collectible')}function isOwned(x){return x.status==='collectible'&&owned.has(key(x))}function isFav(x){return favorites.has(key(x))}
function isWishlist(x){return x.status==='collectible'&&!isOwned(x)}
function wishlistItems(){return collectible().filter(isWishlist)}function record(x){return records[key(x)]||(records[key(x)]={notes:'',condition:'',function:'',box:'',price:'',date:'',place:'',photo:''})}
function renderCard(x){return `<article class="card ${isOwned(x)?'owned':''}" onclick="openModal('${encodeURIComponent(key(x))}')">${isFav(x)?'<div class="favMark">♥</div>':''}${isOwned(x)?'<div class="ownedMark">✓ Lo tengo</div>':''}<div class="pic"><img loading="lazy" src="${esc(x.image)}" alt="${esc(x.name)}" onerror="imgFallback(this)"></div><div class="body"><div class="badge">${esc(x.status_label||x.type||'Furby')}</div><div class="name">${esc(x.name)}</div><div class="meta">${esc(x.collection)}${x.generation?' · '+esc(x.generation):''}${x.year?' · '+esc(x.year):''}</div></div></article>`}
function getFiltered(){const q=$('search').value.toLowerCase().trim(),era=$('era').value,coll=$('collection').value,gen=$('generation').value;let arr=data.filter(x=>{const hay=[x.name,x.collection,x.generation,x.era,x.type].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!era||x.era===era)&&(!coll||x.collection===coll)&&(!gen||x.generation===gen)&&(view==='all'||(view==='collectible'&&x.status==='collectible')||(view==='owned'&&isOwned(x))||(view==='missing'&&x.status==='collectible'&&!owned.has(key(x)))||(view==='wishlist'&&isWishlist(x))||(view==='favorites'&&isFav(x))||(view==='fresh'&&x.status==='fresh')||(view==='prototype'&&x.status==='prototype'))});if(sortMode==='name')arr.sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));else if(sortMode==='yearAsc')arr.sort((a,b)=>(a.year||9999)-(b.year||9999)||String(a.name).localeCompare(String(b.name),'es'));else if(sortMode==='yearDesc')arr.sort((a,b)=>(b.year||0)-(a.year||0)||String(a.name).localeCompare(String(b.name),'es'));else if(sortMode==='era')arr.sort((a,b)=>String(a.era).localeCompare(String(b.era),'es')||String(a.name).localeCompare(String(b.name),'es'));else if(sortMode==='owned')arr.sort((a,b)=>Number(isOwned(b))-Number(isOwned(a)));else if(sortMode==='favorites')arr.sort((a,b)=>Number(isFav(b))-Number(isFav(a)));return arr}
function render(){renderWishlist();renderCatalog();renderCollection();renderHome();renderVitrine();updateStats()}
function renderCatalog(){const arr=getFiltered();$('grid').innerHTML='';const groups={};arr.forEach(x=>{const g=x.generation&&String(x.generation).trim()?x.generation:'Sin generación especificada';(groups[g]??=[]).push(x)});const names=Object.keys(groups);$('generationGroups').innerHTML=names.length?names.map(g=>`<section class="generationGroup" id="gen-${encodeURIComponent(g)}"><div class="generationHead"><h3>🧸 ${esc(g)}</h3><span>${groups[g].length} Furbys</span></div><div class="grid">${groups[g].map(renderCard).join('')}</div></section>`).join(''):'<div class="empty">No encontré Furbys con esos filtros 🥺<br>Prueba con otra búsqueda.</div>'}
function renderCollection(){const arr=collectible().filter(isOwned);$('collectionGrid').innerHTML=arr.length?arr.map(renderCard).join(''):'<div class="empty">Todavía no has añadido Furbys a tu colección. 💜<br>Ve a <b>Catálogo</b> para empezar.</div>';$('collectionCount').textContent=arr.length}
function renderHome(){const arr=collectible().filter(isOwned).slice(-8).reverse();$('homeGrid').innerHTML=arr.length?arr.map(renderCard).join(''):'<div class="empty">Tu colección aparecerá aquí cuando añadas tu primer Furby. 🧸</div>';renderEraStats()}
function renderEraStats(){const eras=unique('era');$('eraStats').innerHTML=eras.map(e=>{const all=collectible().filter(x=>x.era===e),o=all.filter(isOwned).length,p=all.length?Math.round(o/all.length*100):0;return `<button class="eraStat clickable" onclick="openEra(${JSON.stringify(e)})"><div class="eraStatTop"><span>${esc(e)}</span><span>${o}/${all.length}</span></div><div class="progress"><i style="width:${p}%"></i></div><div class="meta" style="margin-top:7px">${p}% de esta era en tu colección · <u>Ver Furbys →</u></div></button>`}).join('')}
function openEra(eraName){goPage('catalog');$('era').value=eraName;view='collectible';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view==='collectible'));$('viewNote').innerHTML="<div class='notice'><strong>🧸 Era seleccionada</strong><br>Mostrando los Furbys coleccionables de "+esc(eraName)+".</div>";$('viewNote').style.display='block';render();window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function clearFilters(){$('search').value='';$('era').value='';$('collection').value='';$('generation').value='';sortMode='default';$('sort').value='default';render()}
function exportBackup(){const payload={version:'2.3',wishlistMode:'automatic',exportedAt:new Date().toISOString(),owned:[...owned],favorites:[...favorites],records};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='furbypedia-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('💾 Respaldo descargado')}
function importBackup(){const f=$('backupInput').files?.[0];if(!f){toast('Selecciona un archivo JSON primero');return}const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(!Array.isArray(p.owned)||!Array.isArray(p.favorites)||typeof p.records!=='object')throw new Error();owned=new Set(p.owned);favorites=new Set(p.favorites);records=p.records||{};saveAll();render();toast('✨ Respaldo restaurado')}catch(e){toast('Ese archivo no parece un respaldo válido')}};rd.readAsText(f)}
function resetCollection(){if(!confirm('¿Borrar tus marcas, favoritos, notas y datos personales de Furbypedia? El catálogo no se eliminará.'))return;owned.clear();favorites.clear();records={};saveAll();render();toast('🧹 Tus datos fueron reiniciados')}
function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null})}else toast('En iPhone: Compartir → Añadir a pantalla de inicio')}
function renderVitrine(){const arr=collectible().filter(x=>isOwned(x)&&record(x).photo);$('vitrineGrid').innerHTML=arr.length?arr.map(x=>`<article class="vitrineItem"><img src="${record(x).photo}" alt="${esc(x.name)}"><div class="vbody"><b>${esc(x.name)}</b><div class="meta">${esc(record(x).place||'Mi colección')}${record(x).price?' · '+esc(record(x).price):''}</div></div></article>`).join(''):'<div class="empty">Añade una foto a tus ejemplares y aparecerán aquí. 📸</div>'}
function renderWishlist(){const arr=wishlistItems();$('wishlistCount').textContent=arr.length; $('wishlistGrid').innerHTML=arr.length?arr.map(renderCard).join(''):'<div class="empty">🎉 ¡Ya tienes todos los Furbys coleccionables de tu catálogo!</div>'}
function updateStats(){const c=collectible().length,o=collectible().filter(isOwned).length,p=c?Math.round(o/c*100):0;$('total').textContent=data.length;$('owned').textContent=o;$('missing').textContent=c-o;$('pct').textContent=p+'%';$('progressBar').style.width=p+'%';$('heroOwned').textContent=o+' en mi colección';$('heroPct').textContent=p+'% completado';$('heroFav').textContent=favorites.size+' favoritos'}
function getNavigableData(){return getFiltered()}
function showFurby(x){if(!x)return;$('dimg').onerror=()=>imgFallback($('dimg'));$('dimg').style.display='block';$('dimg').src=x.image;$('dimg').alt=x.name;$('dtype').textContent=x.status_label||x.type;$('dname').textContent=x.name;$('dtext').textContent=x.characteristics||'';$('dyear').textContent=x.year||'No indicado';$('dera').textContent=x.era||'—';$('dcoll').textContent=x.collection||'—';$('dgen').textContent=x.generation||'No indicado';const r=record(x);const ownedNow=isOwned(x);$('dnotes').value=r.notes||'';$('dBox').value=r.box||'';$('dPrice').value=r.price||'';$('dDate').value=r.date||'';$('dPlace').value=r.place||'';$('dPhotoPreview').src=r.photo||'';$('dPhotoPreview').style.display=r.photo?'block':'none';$('dPhoto').disabled=!ownedNow;$('photoHelp').textContent=ownedNow?'Puedes añadir una foto de tu ejemplar para mostrarlo en Mi vitrina.':'Primero añade este Furby a tu colección para poder subir una foto propia.';document.querySelectorAll('.stateBtn').forEach(b=>b.classList.toggle('active',r[b.dataset.field]===b.dataset.value));$('favBtn').textContent=isFav(x)?'♥ En favoritos':'♡ Añadir a favoritos';const btn=$('ownBtn');if(x.status==='collectible'){btn.style.display='block';btn.textContent=isOwned(x)?'✓ Ya lo tengo — quitar de mi colección':'＋ Añadir a mi colección';btn.classList.toggle('isOwned',isOwned(x));btn.onclick=()=>toggleOwned(x)}else btn.style.display='none';const list=getNavigableData();currentFurbyIndex=list.findIndex(y=>key(y)===key(x));const start=currentFurbyIndex<=0,end=currentFurbyIndex<0||currentFurbyIndex>=list.length-1;$('modalPrev').disabled=start;$('modalNext').disabled=end;currentKey=key(x)}
function openModal(enc){const x=data.find(y=>key(y)===decodeURIComponent(enc));if(!x)return;showFurby(x);$('modal').classList.add('open')}
function navigateFurby(dir){const list=getNavigableData();if(currentFurbyIndex<0)return;const n=currentFurbyIndex+dir;if(n<0||n>=list.length)return;showFurby(list[n])}
function closeModal(){$('modal').classList.remove('open');currentFurbyIndex=-1;currentKey=null}
function toggleOwned(x){if(x.status!=='collectible')return;owned.has(key(x))?owned.delete(key(x)):owned.add(key(x));saveAll();showFurby(x);render()}
function toggleFavorite(){const x=data.find(y=>key(y)===currentKey);if(!x)return;favorites.has(key(x))?favorites.delete(key(x)):favorites.add(key(x));saveAll();showFurby(x);render()}
function saveNotes(){const x=data.find(y=>key(y)===currentKey);if(!x)return;record(x).notes=$('dnotes').value;saveAll()}
function saveCollector(){const x=data.find(y=>key(y)===currentKey);if(!x)return;const r=record(x);r.box=$('dBox').value;r.price=$('dPrice').value;r.date=$('dDate').value;r.place=$('dPlace').value;saveAll();renderVitrine()}
$('favBtn').onclick=toggleFavorite;$('saveNotes').onclick=saveNotes;$('saveCollector').onclick=saveCollector;document.querySelectorAll('.stateBtn').forEach(b=>b.onclick=()=>{const x=data.find(y=>key(y)===currentKey);if(!x)return;record(x)[b.dataset.field]=b.dataset.value;saveAll();showFurby(x)});$('dPhoto').addEventListener('change',e=>{const f=e.target.files?.[0],x=data.find(y=>key(y)===currentKey);if(!f||!x||!isOwned(x))return;const rd=new FileReader();rd.onload=()=>{record(x).photo=rd.result;saveAll();$('dPhotoPreview').src=rd.result;$('dPhotoPreview').style.display='block';renderVitrine()};rd.readAsDataURL(f)});
function openDay(){const x=dayFurby();if(x){goPage('catalog');view='all';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view==='all'));render();openModal(encodeURIComponent(key(x)))} }
function dayFurby(){const c=collectible();if(!c.length)return null;const d=new Date();const seed=d.getFullYear()*10000+(d.getMonth()+1)*100+d.getDate();return c[seed%c.length]}
function renderDay(){const x=dayFurby();if(!x)return;$('dayImg').onerror=()=>imgFallback($('dayImg'));$('dayImg').style.display='block';$('dayImg').src=x.image;$('dayName').textContent=x.name;$('dayMeta').textContent=[x.collection,x.generation,x.year].filter(Boolean).join(' · ')}
function goPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='catalog')render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>goPage(b.dataset.page));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;const notes={collectible:"<div class='notice'><strong>🧸 Coleccionables</strong><br>Los Furbys que forman parte de tu checklist personal.</div>",fresh:"<div class='notice'><strong>📖 Fresh New Look · Historia</strong><br>Referencia histórica; no cuenta para tu colección.</div>",prototype:"<div class='notice'><strong>🔬 Prototipos · Historia</strong><br>Conceptos o modelos no producidos; no se pueden marcar como coleccionados.</div>",favorites:"<div class='notice'><strong>♥ Favoritos</strong><br>Tus Furbys favoritos, sin importar si ya los tienes o todavía están pendientes.</div>",wishlist:"<div class='notice'><strong>♡ Wishlist</strong><br>Todo Furby coleccionable que todavía no tienes aparece automáticamente aquí.</div>"};$('viewNote').innerHTML=notes[view]||'';$('viewNote').style.display=notes[view]?'block':'none';render()});['search','era','collection','generation'].forEach(id=>$(id).addEventListener('input',render));$('sort').addEventListener('change',e=>{sortMode=e.target.value;render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.addEventListener('keydown',e=>{if($('modal').classList.contains('open')){if(e.key==='Escape')closeModal();if(e.key==='ArrowLeft')navigateFurby(-1);if(e.key==='ArrowRight')navigateFurby(1)}});$('modal').addEventListener('touchstart',e=>{if(!e.touches.length)return;touchStartX=e.touches[0].clientX;touchStartY=e.touches[0].clientY},{passive:true});$('modal').addEventListener('touchend',e=>{if(!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.25)navigateFurby(dx<0?1:-1)},{passive:true});
function wishlistShareUrl(){const indexes=wishlistItems().map(x=>data.indexOf(x)).filter(i=>i>=0).join('.');const base=location.href.split('?')[0];return base+'?public=wishlist&ids='+indexes}
async function shareWishlist(){const url=wishlistShareUrl();try{if(navigator.share){await navigator.share({title:'Mi Wishlist de FURBYPEDIA',text:'Mira los Furbys que quiero conseguir 🧸💜',url});}else{await navigator.clipboard.writeText(url);toast('🔗 Enlace copiado');}}catch(e){try{await navigator.clipboard.writeText(url);toast('🔗 Enlace copiado')}catch(_){prompt('Copia este enlace:',url)}}}
function openPublicWishlist(){location.href=wishlistShareUrl()}
function initPublicWishlist(){const params=new URLSearchParams(location.search);if(params.get('public')!=='wishlist')return false;const raw=(params.get('ids')||'').split('.').filter(Boolean);const items=raw.map(v=>{const n=Number(v);return Number.isInteger(n)&&n>=0?data[n]:data.find(x=>key(x)===v)}).filter(x=>x&&x.status==='collectible');document.querySelectorAll('.top,.wrap,.mobileBar,#welcome,#furbypedia-welcome-splash').forEach(el=>el.style.display='none');const box=document.createElement('main');box.id='publicWishlistPage';box.className='wrap';box.style.display='block';box.innerHTML='<div class="heroCard" style="margin-top:30px;text-align:center"><div class="eyebrow">FURBYPEDIA ✦</div><h1>♡ Wishlist</h1><p class="notice">Los Furbys que quiero conseguir para mi colección.</p><span class="chip">'+items.length+' pendientes</span></div><section class="grid" style="margin-top:18px">'+(items.length?items.map(x=>renderCard(x)).join(''):'<div class="empty">Esta wishlist está vacía. 🧸</div>')+'</section><div class="footer">FURBYPEDIA · Wishlist pública</div>';document.body.appendChild(box);return true}
const __publicMode=initPublicWishlist();
function applyTheme(){const t=localStorage.getItem('furbypedia-theme')||'light';document.documentElement.dataset.theme=t;$('themeBtn').textContent=t==='dark'?'☀︎':'☾'}$('themeBtn').onclick=()=>{const n=(localStorage.getItem('furbypedia-theme')||'light')==='dark'?'light':'dark';localStorage.setItem('furbypedia-theme',n);applyTheme()};applyTheme();renderDay();render();
